services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    command: ["uvicorn", "main:app", "--proxy-headers", "--host", "0.0.0.0", "--workers", "4", "--port", "${PORT}"]
    volumes:
      - "./${APPLICATION_DIR}:/root/${APPLICATION_DIR}"
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
